### ISSUE TITLE
1.0 error

### ISSUE THREAD

**Issue by ah-kevin** [vapor/mysql-provider#15]
![image](https://cloud.githubusercontent.com/assets/10068519/18654556/c397dad0-7f14-11e6-9aa1-40fb911ab6e9.png)

**Comment by loganwright** [comment]
@ah-kevin how did you create the xcode project? If you have latest Vapor Toolbox >1.0, then `vapor xcode` will be enough. If you are doing it manually, the mysql headers will have to be linked.

**Comment by ah-kevin** [comment]
![image](https://cloud.githubusercontent.com/assets/10068519/18655360/ce2652be-7f1a-11e6-8c6b-521dc9ae0730.png)
user toolbox 1.0.1  mysql-provider 1.0  
vapor xcode --mysql

**Comment by kaka21garuda** [comment]
@LoganWright I am currently having the same issue as well. When I added this dependency into my Package file, my Xcode couldn't compile due to similar error.
`.Package(url: "https://github.com/vapor/mysql-provider.git", majorVersion: 1, minor: 0)`
I've tried `vapor clean` and `vapor Xcode multiple times`. I am also sure that MySQL server is currently in my local machine.

**Comment by tanner0101** [comment]
Make sure MySQL is installed on your machine by following the instructions at: https://github.com/vapor/mysql
